apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Values.name }}"
  labels:
    name: "{{ .Values.name }}"
    app: "{{ .Values.name }}"
spec:
  containers:
  - image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
    name: "{{ .Values.name }}"
    ports:
    - containerPort: 5001
    env:
    - name: SECRET_NAME
      valueFrom:
        configMapKeyRef:
          name: example-configmap
          key: secret_name
    - name: MEANING_OF_LIFE
      valueFrom:
        configMapKeyRef:
          name: example-configmap
          key: meaning_of_life

