apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
  labels:
    name: "{{ .Values.name }}"
    app: "{{ .Values.name }}"
spec: 
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5001
  selector:
    name: "{{ .Values.name }}"
    app: "{{ .Values.name }}"

